name: My first flow
on: 
  push:
jobs:  
    build_dot_net:
    runs-on: ubuntu-latest
    steps:
    - name: setup golang
      uses: actions/setup-go@v4
      with:
        go-version: ${{vars.GO_VERSION}}

    - name: checkout source
      uses: actions/checkout@v3

    - name: building app
      run: go version