name: My first flow
on: 
  push:
jobs:  
    build_dot_net:
    runs-on: ubuntu-latest
    steps:
    - name: setup dotnet sdk
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{vars.DOTNET_VERSION}}

    - name: checkout source
      uses: actions/checkout@v3

    - name: build app
      run: dotnet build