name: building go application
on: 
  push:
jobs:  
    build_go:
      runs-on: ubuntu-latest
      steps:
      - name: checkout source
        uses: actions/checkout@v3

      - name: deploy railway with secret token
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{secrets.RAILWAY_TOKEN}}
          service: "my-service"