name: building go application
on: 
  push:
    branches:
      - 'master'
      - 'release/v[0-9]+*'
jobs:
    build_go:
      if: "!startswith(github.event.head_commit.message,'#NORUN')"
      runs-on: ubuntu-latest
      steps:

      - name: checking out sources
        uses: actions/checkout@v3

      - name: deploy railway with secret tokens
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{secrets.RAILWAY_TOKEN}}
          service: "shocking-partner"
      
      - name: linking slack with github webhooks
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "DipSA 56 CI/CD Submission",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name:* Choong Hui Ying, Abigail"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Email:* E1112632@u.nus.edu"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Matric Number:* A0127295Y"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ secrets.RAILWAY_URL }}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Go",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "${{ secrets.RAILWAY_URL }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK